### PR TITLE
Gary/extend batch update users email

### PR DESCRIPTION
**Pull request by garethbrickman**
There are two distinct KeyError cases that needed to be handled. The first arises when an old email address is not found or is for a deactivated account. The second arises when a desired new email address is already in use.

The script will have an optional command line argument called "--skip_invalid_emails" that can enable the feature to bypass these KeyErrors and continue looping through the list of member_emails to update.

In order to accommodate the "skip_invalid_emails" feature and to upgrade the default behavior, I inserted try/except blocks so that aborting or continuing the script could be controlled at the points at which the two cases of KeyError could occur. As a side-effect of this, each attempted email update will be POSTed individually rather than combined into a single payload. As a result of this, I could also improve the script's logging so that each update attempt for each email will have its success/fail outcome explicitly printed to the terminal with a reason stated for why if it failed.

Lastly, I improved the default behavior so that when KeyError is excepted the script will abort gracefully with exit code 1.

### CODE REVIEW

**Comment by garethbrickman** [comment]
Example how the script behaves and logs when "skip_invalid_emails" is enabled: 
Screen Shot 2022-08-18 at 12 19 51 AM

Example how the script behaves by default (when feature is not explicitly enabled):
image

**Review by jsjqian — APPROVED** [review]

**Comment by garethbrickman** [comment]
@jsjqian Hey Jack, I've committed a bunch of enhancements and improvements to the script. I've also updated the docs and example CSV.

**Comment by garethbrickman** [comment]
Example of the script's explicit and detailed success and error logging for each update request:

Screen Shot 2022-10-14 at 7 33 59 PM

**Comment by garethbrickman** [comment]
(I don't have write access to this repo so I can't merge pull requests)

**Comment by jsjqian** [comment]
Ah I see, okay I'll go ahead and merge this. Can you ask the IT team as well if they can give you write access? I don't think it should be a big deal.

**Pull request merged**
