### PR TITLE
Add support for emails

### PR DESCRIPTION
**Pull request by jsjqian**

### CODE REVIEW

**Review by deborahc-sigma — APPROVED** [review]

**Review by deborahc-sigma — COMMENTED** [review]
nit: should we call this members_to_update or something like that. and optional but at the end some signal of what succeeded / failed

**Comment by deborahc-sigma** [comment]
> nit: should we call this members_to_update or something like that. and optional but at the end some signal of what succeeded / failed

just learned you can't comment on some collapsed lines in github. i was referring to line 90, `updated_members` variable.

**Comment by deborahc-sigma** [comment]
otherwise lgtm tho

**Review by dqnguyen210 — APPROVED** [review]

**Comment by jsjqian** [comment]
@deborahc-sigma that's a good idea, I can throw that in

**Comment by jsjqian** [comment]
Actually, it'll just crash if it fails haha, I think we're fine here. We can refine it as CS starts using it in the field

**Pull request merged**
